name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
#    - run: npm install
    - run: npm install jest --save-dev
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
        
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.11
      with:
        # The name of the image you would like to push
        name: cloudblog/githubactions:v7
        # The login username for the registry
        username: ${{ secrets.DOCKERHUB_USER }}
        # The login password for the registry
        password: ${{ secrets.DOCKERHUB_PASS }}
        # Use dockerfile when you would like to explicitly build
        dockerfile: Dockerfile
        # Use tag_names when you want to push tags/release by their git name
        tag_names: $(date +%s)
    - name: GitHub Action for Slack
      env:
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      uses: Ilshidur/action-slack@1.6.2
      with:
       args: 'A new commit has been pushed.'
